apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-5q7x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-5q7x
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-5q7x
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-5q7x
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-5q7x
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-psqw-tenant/rhtap-demo-app/hacbs-test-project-5q7x@sha256:0109c0182049b76f18612859ea31315b58c7fda0cc2ea1b4b9d72d70af1588b8
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
